### ISSUE TITLE
Plotting last point

### ISSUE THREAD

**Issue by sunnysideprodcorp** [zerbfra/zfPlotChart#2]
Thank you very much for sharing this! I have been wanting to find something like this for a while. Perhaps I have misread/misunderstood the code, but I think you want the following line as modified:

```
float xGapBetweenTwoPoints = self.chartWidth/MAX(([orderSet count] - 1), 1);
```

when you set xGapBetweenTwoPoints. Otherwise you leave an empty segment at the end of your plot.

**Comment by zerbfra** [comment]
thanks - i will look into it ;)
